### ISSUE TITLE
Style Manager Doesn't Work

### ISSUE THREAD

**Issue by caneser** [viperneo/winforms-modernui#235]
I set up the app via NuGet everything works fine. But I couldnt make the switch theme event work. My code is like below as the MetroFramework.Demo. But idk whats wrong... I need some help.

private void metroTile1_Click(object sender, EventArgs e)
        {
            metroStyleManager.Theme = metroStyleManager.Theme == MetroThemeStyle.Light ? MetroThemeStyle.Dark : MetroThemeStyle.Light;
        }

**Comment by Darknigga** [comment]
you should set the metrostylemanager owner property to your form or do it by code
    
            metroStyleManager.Owner = this;

**Comment by caneser** [comment]
thank you dude, it worked ;)
