### ISSUE TITLE
MetroButton Dark Theme

### ISSUE THREAD

**Issue by tunageXD** [viperneo/winforms-modernui#239]
When using the dark theme for my form and buttons. When buttons are pressed they turn grey but they never turn back to normal without leaving the page and coming back.

Grey button:
![image](https://cloud.githubusercontent.com/assets/10000796/6508864/6c0e8758-c329-11e4-90dd-ed72ddc60dfd.png)

Normal button:
![image](https://cloud.githubusercontent.com/assets/10000796/6508870/723af1fc-c329-11e4-9ff1-f9b5cf90a2e9.png)

**Comment by tunageXD** [comment]
temp solution found

**Comment by Myll** [comment]
What's the solution to this? I'm using the dark theme, when I press a button it just stays grey.

**Comment by DBenS** [comment]
Yes... The grey is due to the Selection in over the button.
I guess there is no other solution than take off the selection from the button.
