### ISSUE TITLE
Tab control Custumization

### ISSUE THREAD

**Issue by akshykhade** [viperneo/winforms-modernui#242]
I want to customize tab control and make that full active rectangle.
i tried but it overrides text.
so, what should i do?
![asd](https://cloud.githubusercontent.com/assets/11384040/6595558/72f2e496-c811-11e4-8b63-ec174a76b861.png)

**Comment by akshykhade** [comment]
Finally Done..
![after change](https://cloud.githubusercontent.com/assets/11384040/6613748/26f42be4-c8b7-11e4-92cd-2547ddb846b1.png)

**Comment by tunageXD** [comment]
How did you get it to work?

**Comment by tunageXD** [comment]
Very interested in this feature!!

**Comment by akshykhade** [comment]
Some changes in <B>MetroTabControl.cs</B>

**Comment by tunageXD** [comment]
I don't see any changes on github.

**Comment by akshykhade** [comment]
Because didn't sync. it.. ...

code:
<b>changes in metrotabcontrol.cs</b> 

 protected virtual void OnPaintForeground(PaintEventArgs e)
        {
            for (var index = 0; index < TabPages.Count; index++)
            {
                if (index != SelectedIndex)
                {
                    DrawTab(index, e.Graphics);
                }
            }
            if (SelectedIndex <= -1)
            {
                return;
            }
            DrawTabBottomBorder(SelectedIndex, e.Graphics);  <b>
            DrawTabSelected(SelectedIndex, e.Graphics);
            DrawTab(SelectedIndex, e.Graphics);</b>
            OnCustomPaintForeground(new MetroPaintEventArgs(Color.Empty, Color.Empty, e.Graphics));
        }
<br><br>
 private void DrawTabSelected(int index, Graphics graphics)
        {
            using (Brush selectionBrush = new SolidBrush(MetroPaint.GetStyleColor(Style)))
            {
                Rectangle selectedTabRect = GetTabRect(index);<b> 
   Rectangle borderRectangle = new Rectangle(selectedTabRect.X + ((index == 0) ? 2 : 0), GetTabRect(index).Top + 2 - TabBottomBorderHeight, selectedTabRect.Width + ((index == 0) ? 0 : 2),  GetTabRect(index).Height+2); </b>
               graphics.FillRectangle(selectionBrush, borderRectangle);
            }
        }

**Comment by tunageXD** [comment]
Thanks so much!
