### ISSUE TITLE
How can I make my form as fixed size?

### ISSUE THREAD

**Issue by sappho192** [viperneo/winforms-modernui#256]
In System.Windows.Forms, I can make my form fixed by

    this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;

but how can I do this in MetroFramework?
What I found is

    MetroFramework.Forms.MetroFormBorderStyle.FixedSingle;  
but I don't know how can I use this. I tried
    
    this.FormBorderStyle = (System.Windows.Forms.FormBorderStyle)MetroFramework.Forms.MetroFormBorderStyle.FixedSingle;

but it shows 

![image](https://cloud.githubusercontent.com/assets/7788738/7016517/e6918730-dd20-11e4-8c1c-ca5ee24d9329.png)  
Can anyone help me?

**Comment by Jose-Alberto-G-R** [comment]
Sets the property of the form "Resize" = true and "SizeGripStyle" = show, you do not need the code for borderFixed, you can resize from the bottom right corner

**Comment by sappho192** [comment]
You mean change "Resizable" as False and "SizeGripStyle" as Hide? Thanks! I solved it :)
