### ISSUE TITLE
how to add tooltip programmatically

### ISSUE THREAD

**Issue by bhaveshsorathiya1** [viperneo/winforms-modernui#271]
how to add tooltip text programmatically

**Comment by Jose-Alberto-G-R** [comment]
An Example for vb.net

Dim myToolTip As MetroFramework.Components.MetroToolTip = New MetroFramework.Components.MetroToolTip()

myToolTip.SetToolTip(btnClose, "Close")

But ... why did not add it with the designer?

**Comment by bhaveshsorathiya1** [comment]
THANK YOU... :)

**Comment by bhaveshsorathiya1** [comment]
How To Add Metro Control In MetroGrid Column.
