### ISSUE TITLE
How to loop through form controls?

### ISSUE THREAD

**Issue by Michelh91** [viperneo/winforms-modernui#276]
Hi. 

I am trying to loop through Form controls with this code:

Dim ctl As Control
For Each ctl In Me.Controls
'Do stuff here
Next

But in Me.Controls I am only getting standard windows forms controls.

How can I loop through MetroFramework.Controls?

Thank you

**Comment by dennismagno** [comment]
The piece of code that you attached will just loop through the controls attached to the form.  But if the MetroFramework controls is inside a panel or another controls you need to loop to the panel just like this

For Each ctl In panel1.Controls
'Do stuff here
Next

**Comment by ppn123** [comment]
You can try this way
 foreach (Control frmitems in this.Controls)
                {
                    if (frmitems  is MetroFramework.Controls.MetroTextBox)
                    {
                        // do stuff 
                    }
                }

**Comment by Michelh91** [comment]
Solved, thank you!
