### ISSUE TITLE
MetroMessageBox.Show

### ISSUE THREAD

**Issue by ayoubleg** [viperneo/winforms-modernui#287]
Hi !
I've tried again and again but i can't get it :/
(tried to record with OBS but it failed ... ^^")
So it's simple ... I can create a messabox on the top of my  main form , all actions are interrupted while messagebox isn't closed (what i want).
You can't clic on the mainform while messagebox isn't closed (windows warning sound(cool too)).
BUT, if i click on my mainfrom thought the taskbar, the mainform get the focus at top and the messagebox get behind this :/ then you can't close the messagebox and the program , can't alt+f4 ... have to kill process :<
Anyone have an idea ?
I use it like this : 
```
if (Stuff() == -42)
   MetroFramework.MetroMessageBox.Show(this, "File not found!", "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
```
In a TimerTick (disabled while it's processing)
PS : If i pause the program (Visual Studio) it's stuck at this line too.

**Comment by edleyrocha** [comment]
Post something about the code; Something else.
To understand the code.

**Comment by ayoubleg** [comment]
Okay ! 
```csharp
        private void timer1_Tick(object sender, EventArgs e)
        {
            this.timer1.Enabled = false;
            GetWindowText(stuff, Buff, nChars);
            if (IsWindow(stuff))
            {
                if (Buff.ToString() != "Something")
                {
                    if (Stuff() == -42)
                        MetroFramework.MetroMessageBox.Show(this, "File not found!", "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
                this.timer1.Enabled = true;
            }
            else
                this.timer2.Enabled = true;
                stuff here...
        }
```
It's something like that :p
I try to make a video brb :)

**Comment by ayoubleg** [comment]
OK ! Fixed this simply ... Forgot that was open source 'lol'
Just go to MetroFramework->MessageBox->MetroMessageBox.cs and added "_control.TopMost = true;"

**Comment by edleyrocha** [comment]
Good

**Comment by ayoubleg** [comment]
Also added this to match my preference ! I love open source <3
```csharp
                if (_owner.WindowState == FormWindowState.Minimized)
                {
                    _control.Text = title;
                    _control.Icon = _owner.Icon;
                    _control.ShowInTaskbar = true;
                    _control.Size = new Size(400, 200);
                    _control.Location = new Point((Screen.PrimaryScreen.WorkingArea.Width - _control.Width) / 2, (Screen.PrimaryScreen.WorkingArea.Height - _control.Height) / 2);
                }```
