### ISSUE TITLE
MetroComboBox dropdown list background color

### ISSUE THREAD

**Issue by FatimaRmayhi** [viperneo/winforms-modernui#289]
Sometimes, this issue occurs with my project:
1- open a form containing many controls (a combobox + 2 buttons for example).
2- Press Tab to move between controls.
3- click on the combobox, dropdownlist background color is colored by Style color.

Find the screenshot below
the style I used is blue, if you use Orange style color, the items will be colored in orange.

![screenshot](https://cloud.githubusercontent.com/assets/13048540/8375955/b7fd0a38-1c0a-11e5-952d-a92dea6d4063.png)

**Comment by Jose-Alberto-G-R** [comment]
Same problem

**Comment by mobedi** [comment]
I also have the same problem.

**Comment by FatimaRmayhi** [comment]
I found the solution:
In MetroFrameWork project, MetroComboBox.cs class, OnDrawItem function:
Replace the following lines:
if (e.State == (DrawItemState.NoAccelerator | DrawItemState.NoFocusRect) || e.State == DrawItemState.None)
                {
                    using (SolidBrush b = new SolidBrush(backColor))
                    {
                        e.Graphics.FillRectangle(b, new Rectangle(e.Bounds.Left, e.Bounds.Top, e.Bounds.Width, e.Bounds.Height));
                    }

                    foreColor = MetroPaint.ForeColor.Link.Normal(Theme);
                }
                else
                {
                    using (SolidBrush b = new SolidBrush(MetroPaint.GetStyleColor(Style)))
                    {
                        e.Graphics.FillRectangle(b, new Rectangle(e.Bounds.Left, e.Bounds.Top, e.Bounds.Width, e.Bounds.Height));
                    }

                    foreColor = MetroPaint.ForeColor.Tile.Normal(Theme);
                }

By:
if ((e.State & DrawItemState.Selected) == DrawItemState.Selected)
                {
                    using (SolidBrush b = new SolidBrush(MetroPaint.GetStyleColor(Style)))
                    {
                        e.Graphics.FillRectangle(b, new Rectangle(e.Bounds.Left, e.Bounds.Top, e.Bounds.Width, e.Bounds.Height));
                    }

                    foreColor = MetroPaint.ForeColor.Tile.Normal(Theme);
                }
                else
                {
                    using (SolidBrush b = new SolidBrush(backColor))
                    {
                        e.Graphics.FillRectangle(b, new Rectangle(e.Bounds.Left, e.Bounds.Top, e.Bounds.Width, e.Bounds.Height));
                    }

                    foreColor = MetroPaint.ForeColor.Link.Normal(Theme);
                }

**Comment by Jose-Alberto-G-R** [comment]
Nice, TY works for me

**Comment by dennismagno** [comment]
@FatimaRmayhi  Nice fix. Thanks.

**Comment by buddhikaprasad** [comment]
(y)
