### ISSUE TITLE
Problems at execution time of Metroframework .NET 4 compiled version.

### ISSUE THREAD

**Issue by DBenS** [viperneo/winforms-modernui#293]
I tried to compile Metroframework to the .NET 4 (full). The compilation happened 100% but when I tried to call any form in my 2013 VB project (initial loading), I got an exception error:

<b><i>Fail in the security transparent Method: MetroFramework.Forms.MetroForm.WndProc(System. WIndows.Forms.Message ByRef) in access to the security critical method "System.Runtime.InteropServices.Marshal.StructureToPtr(System.Object, IntPtr, Boolean)"

I researched the problem and finally I found the ACTUAL problem - that is not related to the FORMS.Metroform.cs as I had supposed to, since the function is called from it. It´s related to the OLD FASHION way to allow "Partially Trusted Callers" to call the SYSTEM function. 

Follows the steps to correct it and get success execution in .NET 4 compiled Metroframework:

- Open each project of Metroframework and change the target framework to .NET 4 (I don´t like the client version of any .NET).
- Mark all of them as "Allow Unsafe Code".
- Rebuild them in Release Mode.
- Open the AssemblyInfo.cs of Metroframework Project - only that.
- Locate the line [assembly:AllowPartiallyTrustedCallers]
- Remark this line with //.
- Recompile the solution.

Doing so, I can merge Metroframework .NET 4 into my .NET 4 application without the problem as shown above.

I hope it can help someone else.
Kind regards.

PS: just for additional info, you may see the following links about it:
https://msdn.microsoft.com/en-us/library/system.security.allowpartiallytrustedcallersattribute(v=vs.110).aspx

https://msdn.microsoft.com/en-us/library/bfz783fz(v=vs.110).aspx

**Comment by PeterKenyon** [comment]
see my earlier post security issue using .NET 4.5 #286 this is the same problem I believe

**Comment by DBenS** [comment]
I guess it is. 

But anyway, the "AllowPartiallyTrustedCallers" in Assembly is an old and obsolete mode for .NET 4.xx (and I guess even 3.5). 

Kind regards Peter.
