### ISSUE TITLE
Metrogrid not showing its borders

### ISSUE THREAD

**Issue by DBenS** [viperneo/winforms-modernui#295]
When we put a Metrogrid in a form with its own borders active (via Metrogrid Properties Page), when we close and reopen the form (even in Visual Studio) the grid appears borderless.

It occurs also during the runtime. I guess the PAINT event is setting a default value (no borders).

Best Regards

**Comment by dennismagno** [comment]
When I created this MetroGrid, I intentionally removed the border to make it more suitable with the theme just like MetroTab which also doesn't have border.  You can easily add the border through code by adding the border on the grid after initialize

**Comment by DBenS** [comment]
Hi Denis, nice to meet you.

It´s ok, I see the logic behind your choice. But if the control properties contains the settings and shows the border in Design Mode, I guess to be coerent, to give the option really functioning as shown in Design Mode.

Yes, I set the border directly into the code but the way I do I have no choice (no runtime parameter) - all grids will be bordered. I´m not experienced with C# and I couldn´t see exactly how (and where) build the Property within code.

Anyway, thank you for your answer.
Kind regards.
