### ISSUE TITLE
Form opacity does not change by code

### ISSUE THREAD

**Issue by mobedi** [viperneo/winforms-modernui#296]
So is it true that we cannot change a form's opacity by code?

When I set my form's opacity in Design mode, the form appears with the correct opacity, but when I set this value in the program, I don't see the effect. Does anyone have the same problem?

**Comment by DBenS** [comment]
No, it´s not true.

You can change opacity by code, BUT, differently from design-mode, it is scale from 0.0 to 1.0 and not from 0% to 100%.

The only problem I noted is the one related into #291.

Regards.

**Comment by mobedi** [comment]
@DBenS true. thank you!

**Comment by DBenS** [comment]
You´re welcome. All of us can help ourselves in some time.
Regards!  Close this Issue...
