### ISSUE TITLE
Autosized/Right-Aligned Labels not functioning

### ISSUE THREAD

**Issue by DBenS** [viperneo/winforms-modernui#302]
If we put labels right-aligned (Property *TextAlign = TopRight*) and with the property *Autosize=True* in DesignMode, and we change the label *Text* property programmatically (eg. different languages like English and Portuguese), the labels do not change accordingly.

The right thing is to have the labels growing their sizes from right-to-left to accomodate the new contents. But it´s not true...  It seems the labels grow but from left-to-right, discarding completely the *TextAlign* property.

**Comment by dennismagno** [comment]
I think this also happens using the default label from Visual Studio.

**Comment by DBenS** [comment]
Damn!
You´re right Denis...  How can MS make that mistake and NEVER had corrected it?
Thanks Denis.
Closing that issue...
