### ISSUE TITLE
What are the MetroFramework.Design and MetroFramework.Font projects for?

### ISSUE THREAD

**Issue by mobedi** [viperneo/winforms-modernui#305]
The Github solution comprises four projects: One is the main library, one the demo project and two other projects called *Design*  and *Font* that reference the main library. What are they for? Can one use the *MetroFramework* library without them?

**Comment by DBenS** [comment]
You need all of them (their DLL files, at least) referenced into your project.

**Comment by mobedi** [comment]
@DBenS I just noticed that if I don't reference *Design* in my project I cannot drag-n-drop controls in my forms. But what is *Font* doing?

**Comment by DBenS** [comment]
@mobedi , you need to read the docs of the project - or see the demo. Did you see the videos in the main page?

**Comment by mobedi** [comment]
@DBenS I saw the video but didn't read the docs.
