### ISSUE TITLE
Scrollbar on main form causes UI issues

### ISSUE THREAD

**Issue by amorpeth** [viperneo/winforms-modernui#307]
Hey,

Are scrollbars supported on the main form? When I enable the "AutoScroll" property on the form I get some bizarre issues with the forms UI. I am trying to make my app fit 1024x768 res so need vertical scrollbars to achieve this.

![scroll](https://cloud.githubusercontent.com/assets/10904996/8767471/1b27ca80-2eb2-11e5-858c-da3f4d2ae128.jpg)

I see there is also a scrollbar control, however I am unsure how I could make this work on the form. If this is a solution is there any documentation you can point me to?

Thanks,
Andrew

**Comment by luciusmagn** [comment]
Try putting the whole thing into one big panel, then add scrollbar to the panel

**Comment by amorpeth** [comment]
Legend that sorted it!! I was sure I tried that, however I may have been using an older fork. I updated to 1.3 and all tested OK :)

**Comment by DBenS** [comment]
@amorpeth , if it´s solved please close it.
Hugs!
