### ISSUE TITLE
MetroMessageBox

### ISSUE THREAD

**Issue by alexeycas6** [viperneo/winforms-modernui#315]
How to change style of MetroMessageBox? Default is black.

**Comment by dennismagno** [comment]
Change the parameter being passed on the icon.

Green: MessageBoxIcon.Question
Blue: MessageBoxIcon.Asterik,  MessageBoxIcon.Information
Red: MessageBoxIcon.Error,  MessageBoxIcon.Hand,  MessageBoxIcon.Stop
Orange: MessageBoxIcon.Exclamation,  MessageBoxIcon.Warning
Gray:  MessageBoxIcon.None

**Comment by alexeycas6** [comment]
Thanks
