### ISSUE TITLE
DateTimePicker appearing as Windows

### ISSUE THREAD

**Issue by DBenS** [viperneo/winforms-modernui#316]
I put the DateTimePicker in a form and I call it using ShowDialog()

The control is appearing with double-border at runtime ONLY and when we click on it to select a new date, the control suddenly appears like Windows one: the arrow and the calendar, as shown below:

![image](https://cloud.githubusercontent.com/assets/13090884/9198798/f717cb12-4014-11e5-8de7-056b1d49f890.png)

How can I solve it?
Is the problem related to ShowDialog?

Regards!

**Comment by DBenS** [comment]
It seems the INVALIDATE command is not functioning as should, to redraw the control....  :-1:

**Comment by Onerky** [comment]
To correct this issue, at least for me i resolve it uncommenting the lines 
Application.EnableVisualStyles();
Application.SetCompatibleTextRenderingDefault(false);

that are located in the Program.cs file because the style of the Metro ui is inheriting from the .net framework 

regards

**Comment by DBenS** [comment]
Where PROGRAM.CS is within the project? I can´t locate it...

**Comment by Onerky** [comment]
yes!! is the main cs file that allow you to initialize the 1st form created, is located in the right bar in the solution explorer you can search it

**Comment by DBenS** [comment]
Onerky, I´m really sorry but my solution has no PROGRAM.CS outside the DEMO project.

Could you please be more specific?  I have NO ONE MAIN.CS and the only PROGRAM.CS is inside the DEMO project.  WHich file are we talking about and in what project (MetroFramework or MetroFramewrok.Design)?

And my own project is a VB.NET one, not a C#...

Thank you!

**Comment by Onerky** [comment]
ohhh you have said it before. well in this case, have you disable something or by default its working bad this component? However im gonna check in my VS with a VB proyect

**Comment by DBenS** [comment]
The DEMO is working 100% here BUT when I put the DATETIME within my VB project, it appears 100% during DESIGN TIME and at EXECUTION TIME since you don´t click on it!  When you click to select a new date, (boom!), its design goes back to Windows default.  Amazing!

**Comment by Onerky** [comment]
give me some minutes im on it

**Comment by DBenS** [comment]
The properties of DATETIME inside the original C# Project is EXACTLY THE SAME I have in my own VB project...

Thank you VERY MUCH!

**Comment by Onerky** [comment]
No men. You are doing something wrong, i try and i have no issues with the MetroDateTimePicker

**Comment by DBenS** [comment]
It´s amazing!  All controls are functioning OK, but not this one...

The ONLY thing I have is MetroStyleManager in all forms, to handle the default Style and Theme I set inside the program. And everything is OK....

Thank you VERY MUCH for your help, but I really don´t know what to check anymore - I made a "chinese debug" on it and I didn´t find any trouble.

I really had appreciated your efforts and patience to help me. Thanks a LOT!

**Comment by DBenS** [comment]
Onerky, yes, I can send the form to you by mail.  Can you inform it to me?

**Comment by Onerky** [comment]
of course, no problem

**Comment by DBenS** [comment]
Sent Onerky.

**Comment by Onerky** [comment]
nop. it hasnt arrive yet

**Comment by DBenS** [comment]
Sent by Gmail. Let me see if we had any trouble...

**Comment by DBenS** [comment]
You may download it from:  www.oasys.com.br/ForOnerky.rar

**Comment by DBenS** [comment]
Here too in Brazil...  Have a good night and thanks again Onerky!  I´ll see you tomorrow.

**Comment by Onerky** [comment]
i guess you removed the link for security reasons (because i cannot download), so tell me when it is available to dowload.

**Comment by DBenS** [comment]
Onerky, I hadn´t remove it!
Let me check it.

**Comment by dennismagno** [comment]
My guest is you disable Enable Application Framework under Settings->Application to start your app using Sub Main? Is that correct? 
![dtpickerissue](https://cloud.githubusercontent.com/assets/5070675/9358355/20a2c888-46be-11e5-9d03-9038a4c7c3e9.JPG)

If thats the case, before you call your first form add this Application.EnableVisualStyles()

**Comment by DBenS** [comment]
:100:    You´re 50% right @dennismagno .

The "Enable Application Framework" is enabled in the project (.NET 4.0), without solve the proble,.
But, when I added the line "Application.EnableVisualStyles" as the first line of the first form (FORM1), the control behaviour seemed to be ok.

Thanks for the support!
And thanks A LOT to @Onerky to try a solution together with me.

Hugs to both!
