### ISSUE TITLE
Cant add MetroTabContrl & MetroTile 

### ISSUE THREAD

**Issue by oghenez** [viperneo/winforms-modernui#317]
I tried adding these controls mentioned, and some others,but they dont appear on the form. SOme others like the grid, datepicker, trackbar panel was addd thought
I am using vs 2008, .net 2.0
Regards

**Comment by dennismagno** [comment]
Make sure all the 3 DLL's are added as a reference on your project.

**Comment by oghenez** [comment]
Thanks

**Comment by mrsaeedkp** [comment]
Step1 . Add control
Step2. Import library (design & font)
