### ISSUE TITLE
The grey thick frame around the form when it loses focus

### ISSUE THREAD

**Issue by mobedi** [viperneo/winforms-modernui#320]
I would first have to admit that is probably not an issue with the master code, but probably because I started using a fork of the code. Because I did not have this issue the last time I used the library. But now it has become quite a GUI glitch.

It is about the grey thick frame that appears on the form when it loses focus. Again, this does not happen all the time so I am still yet to figure out the reason. But does anyone else have this issue or has a way to fix it? It makes my form look glitch-y and sometimes does not go away.

**Comment by bhaveshsorathiya1** [comment]
please use this project dll.

https://github.com/dennismagno/winforms-modernui

**Comment by mobedi** [comment]
@bhaveshsorathiya1 I will. Thanks. Just wondering if the problem with DataGridView scrolling crashes is fixed in this version? I am talking about https://github.com/viperneo/winforms-modernui/issues/275?

**Comment by mobedi** [comment]
@bhaveshsorathiya1 I replaced the library you mentioned. It looks better but now I am receiving `NullReferenceExceptions` on some places where I am trying to change my form's `ShowInTaskbar` and `Visible` properties. Any idea how to handle them?

**Comment by dennismagno** [comment]
Can you share more details about your problem? I just downloaded my fork and got no problem at all.

**Comment by mobedi** [comment]
@dennismagno It's strange. It works fine when I run the Demo project. But not when I have it in my own solution. The only difference I can see is that the demo solution uses `.Net Framework 2.0` and `AnyCPU` whereas mine uses `.NET Framework 4.5` and `x64`. But this has always been like that so that should not be a problem.

**Comment by dennismagno** [comment]
Oh maybe thats why, I havent tried .net framework 4.5.  I will try it out.

**Comment by mobedi** [comment]
Great! Please come back if you encountered the same problems.

**Comment by mobedi** [comment]
@dennismagno When I change all MetroFramwork solution projects to `.NET 4.5` and run the demo project I get a `MethodAccessException` on `Program.cs` that reads: "Attempt by security transparent method 'MetroFramework.Forms.MetroForm.OnActivated(System.EventArgs)' to call native code through method 'MetroFramework.Native.DwmApi.DwmSetWindowAttribute(IntPtr, Int32, Int32 ByRef, Int32)' failed.  Methods must be security critical or security safe-critical to call native code."

**Comment by dennismagno** [comment]
I havent encounter any issue.  What I did is I compile the project with the default framework and cofiguration.  Created new project in VS2015 with .net framwork 4.5.2 and x64, add the 3 DLL's as reference add the MetroFramework.dll in toolbar.  Change my form into MetroForm execute the program and it works as expected.

**Comment by mobedi** [comment]
@dennismagno OK. Thanks! I dunno what I am doing wrong then.

**Comment by mobedi** [comment]
@dennismagno I just re-downloaded the master library and this one seems to be working. I didn't see the error fix comments on the commits so I thought they were overlooked but he has apparently fixed all the issues now.
