### ISSUE TITLE
Form Size Increases With Clicks On Program's Taskbar Icon

### ISSUE THREAD

**Issue by mobedi** [viperneo/winforms-modernui#323]
This is from the latest commit of the master code.

At first I thought it's a glitch that happens because of my code. But I created an empty solution with one `MetroForm`, built and run the app. Then started clicking on the program's taskbar icon. Every time you see the form, it's slightly bigger. 

Has anyone else encountered this?

**Comment by DBenS** [comment]
In VB.NET I´m having the same issue. Each time the form minimize/restore throught the taskbar icon, it grows its size alone...

**Comment by DBenS** [comment]
And the original project does the same behaviour - it´s an intrinsic problem in Metroframework.

**Comment by mobedi** [comment]
@DBenS But I didn't have it in the other program I made about a year back.

**Comment by DBenS** [comment]
Should it due to Shadow implementation?

**Comment by mobedi** [comment]
@DBenS How were you able to fix it?

**Comment by DBenS** [comment]
I didn´t fix it!  I´m looking the code to see what can be happening - but I´m a VB programmer, not a C# one and the code is a little bit confuse to me.  Anyway, I´m looking the original project.

**Comment by mobedi** [comment]
@DBenS Thanks!

**Comment by DBenS** [comment]
I got it, I guess...

The problem is related to AeroWindowSnapActive.
**If you disable it, the problem stops!**

The line responsible to this is:

** Metroform.cs  in  Metroframework**

     case (int)WinApi.Messages.WM_NCCALCSIZE:
                >>>   if (isAeroWindowSnapActive)   <<<
                    {
                        if (m.WParam.Equals(IntPtr.Zero))
                        {

                            WinApi.RECT rc = (WinApi.RECT)m.GetLParam(typeof(WinApi.RECT));
                            Rectangle r = rc.ToRectangle();
                            r.Inflate(7, 7);
                            System.Runtime.InteropServices.Marshal.StructureToPtr(new WinApi.RECT(r), m.LParam, true);
                        }
                        else
                        {
                            WinApi.NCCALCSIZE_PARAMS csp = (WinApi.NCCALCSIZE_PARAMS)m.GetLParam(typeof(WinApi.NCCALCSIZE_PARAMS));
                            Rectangle r = csp.rect0.ToRectangle();
                       >>>  r.Inflate(7, 7);   <<<
                            csp.rect0 = new WinApi.RECT(r);
                            System.Runtime.InteropServices.Marshal.StructureToPtr(csp, m.LParam, true);
                        }
                    }
                    m.Result = IntPtr.Zero;
                    break;

**Comment by DBenS** [comment]
I returned to my VB project and disabled the properety *AeroWindowSnapActive* of my form.
The problem stops...  :100:

**Comment by mobedi** [comment]
@DBenS Genius! May I ask how you found it out?

**Comment by mobedi** [comment]
@DBenS I think the old version of framework did not have this property because I cannot see it in my old program. That's why it was never encountered by me.

**Comment by mobedi** [comment]
@DBenS Am I dreaming or does setting `AeroWindowSnapActive` to `false` also fixes https://github.com/viperneo/winforms-modernui/issues/322?

**Comment by DBenS** [comment]
@mobedi , I just opened the DEMO project and follow the TASKBAR.CS and METROFORM.CS events . If we put some breakpoints in some events (at least, most of them), we can see exactly what is happening.  

Of course, you have to have some experience/feeling with "weird programming issues" (I´m an old man, but not obsolete  :) ) and when I say the lines above, specially the *r.inflate* I made some tests with *r.inflate(0,0)* and *r.inflate(17,17)*.  Since the form had changed its design, I saw the commands are related to thi property and if you pay attention, you will see the size parameters (**rc** and **csp**)  differs in the calculation mode.

Of course, a good dose of luck...  :)

**Comment by mobedi** [comment]
@DBenS your comments are always very helpful. Thanks again.
