### ISSUE TITLE
How set tooltip to Datagridview?

### ISSUE THREAD

**Issue by DBenS** [viperneo/winforms-modernui#329]
In my application I set the Tooltip text at runtime, since the user can choose among 3 different languages. I do not utilize the MetroTooltip since it has some bugs related to the size of tooltip versus its contents.

The program functions perfectly, where I set:

       ToolTip1.SetToolTip(Me.Control, MessageToDisplay)

But doing so to any MetroDatagridview does not function.
Putting the mouse over the grid does not fire the Tooltip event.

Does someone know how to do it?
Tks!

**Comment by dennismagno** [comment]
You can try it this wat.  DataGridView1.Columns(0).ToolTipText = "Sample"

**Comment by DBenS** [comment]
Hi Denis.
I would like to have a general tooltip in entire DataGridView - and I got success using the MetroTooltip, but not the VS Tooltip.
Anyway, my problem is solved, thank you for support.
